# Generated by Django 4.2.7 on 2023-11-24 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StakeHolders', '0013_remove_student_signature_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('physically_present', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StakeHolders.student')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField()),
                ('present_student_count', models.IntegerField()),
                ('absent_student_count', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('attendance', models.ManyToManyField(blank=True, to='Session.attendance')),
                ('total_students', models.ManyToManyField(blank=True, to='StakeHolders.student')),
            ],
        ),
    ]
