# Generated by Django 4.2.7 on 2023-11-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='absent_student_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='present_student_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
