# Generated by Django 4.2.7 on 2023-11-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0002_alter_session_absent_student_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='attendance',
            field=models.ManyToManyField(blank=True, null=True, to='Session.attendance'),
        ),
    ]
