# Generated by Django 4.2.7 on 2023-11-24 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0003_alter_session_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 24, 19, 11, 27, 301723)),
            preserve_default=False,
        ),
    ]
