# Generated by Django 4.2.7 on 2023-12-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Manage', '0001_initial'),
        ('TimeTable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='time_table',
            field=models.ManyToManyField(blank=True, to='TimeTable.timetable'),
        ),
        migrations.AddField(
            model_name='college',
            name='branches',
            field=models.ManyToManyField(blank=True, to='Manage.branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='batches',
            field=models.ManyToManyField(blank=True, to='Manage.batch'),
        ),
        migrations.AddField(
            model_name='batch',
            name='semesters',
            field=models.ManyToManyField(blank=True, to='Manage.semester'),
        ),
    ]
