# Generated by Django 4.2.7 on 2024-01-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='end_year',
            field=models.CharField(default=2023, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_year',
            field=models.CharField(default=2023, max_length=4),
            preserve_default=False,
        ),
    ]
