# Generated by Django 4.2.7 on 2024-10-28 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0030_college_super_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='type',
        ),
        migrations.AddField(
            model_name='college',
            name='code',
            field=models.PositiveBigIntegerField(default='028'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 10, 28)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 10, 28)),
            preserve_default=False,
        ),
    ]
