# Generated by Django 4.2.7 on 2024-10-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0031_remove_term_type_college_code_semester_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='code',
            field=models.CharField(max_length=3),
        ),
    ]
