# Generated by Django 4.2.7 on 2024-10-30 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0032_alter_college_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='college',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='term',
        ),
        migrations.RemoveField(
            model_name='term',
            name='branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manage.term'),
        ),
        migrations.AddField(
            model_name='semester',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manage.branch'),
        ),
        migrations.AddField(
            model_name='term',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Manage.college'),
        ),
    ]
