# Generated by Django 4.2.7 on 2024-10-30 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0033_remove_branch_college_remove_semester_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.college'),
        ),
    ]
