# Generated by Django 4.2.7 on 2024-10-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0035_remove_classroom_branch_classroom_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='short_name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
