# Generated by Django 4.2.7 on 2024-11-01 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0015_teacher_teacher_code'),
        ('Manage', '0036_subject_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='students',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='branch',
        ),
        migrations.AlterField(
            model_name='subject',
            name='short_name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.branch')),
                ('students', models.ManyToManyField(blank=True, to='StakeHolders.student')),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manage.stream'),
        ),
    ]
