# Generated by Django 4.2.7 on 2024-11-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0037_remove_branch_students_remove_semester_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
