# Generated by Django 4.2.7 on 2024-11-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0039_stream_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stream',
            name='title',
            field=models.CharField(choices=[('BE', "Bachelor's"), ('ME', "Master's")], max_length=20),
        ),
    ]
