# Generated by Django 4.2.7 on 2024-11-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0040_semester_finalized_alter_stream_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='finalized',
        ),
        migrations.AddField(
            model_name='subject',
            name='E',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='I',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='L',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='M',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='P',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='T',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='V',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='eff_from',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_functional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_practical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_semipractical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_theory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='practical_exam_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='theory_exam_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
