# Generated by Django 4.2.7 on 2024-11-07 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0041_remove_semester_finalized_subject_e_subject_i_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('eff_from', models.CharField(blank=True, max_length=20, null=True)),
                ('subject_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('L', models.PositiveIntegerField(blank=True, null=True)),
                ('P', models.PositiveIntegerField(blank=True, null=True)),
                ('T', models.PositiveIntegerField(blank=True, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
                ('E', models.PositiveIntegerField(blank=True, null=True)),
                ('M', models.PositiveIntegerField(blank=True, null=True)),
                ('I', models.PositiveIntegerField(blank=True, null=True)),
                ('V', models.PositiveIntegerField(blank=True, null=True)),
                ('total_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('is_elective', models.BooleanField(default=False)),
                ('is_practical', models.BooleanField(default=False)),
                ('is_theory', models.BooleanField(default=False)),
                ('is_semipractical', models.BooleanField(default=False)),
                ('is_functional', models.BooleanField(default=False)),
                ('practical_exam_duration', models.FloatField(blank=True, null=True)),
                ('theory_exam_duration', models.FloatField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('finalized', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='E',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='I',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='L',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='M',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='P',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='T',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='V',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='eff_from',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='finalized',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_elective',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_functional',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_practical',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_semipractical',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_theory',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='practical_exam_duration',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='theory_exam_duration',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manage.permanentsubject'),
        ),
    ]
