# Generated by Django 4.2.7 on 2024-11-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0042_permanentsubject_remove_subject_e_remove_subject_i_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permanentsubject',
            old_name='code',
            new_name='subject_code',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='branch_code',
        ),
        migrations.AddField(
            model_name='permanentsubject',
            name='sem_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permanentsubject',
            name='stream_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='stream_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='branch',
            field=models.ManyToManyField(to='Manage.branch'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('stream_code', 'branch'), name='unique_stream_code_in_term'),
        ),
    ]
