# Generated by Django 4.2.7 on 2024-11-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0043_rename_code_permanentsubject_subject_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permanentsubject',
            name='finalized',
        ),
    ]
