# Generated by Django 4.2.7 on 2024-11-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0045_alter_permanentsubject_practical_exam_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permanentsubject',
            name='subject_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
