# Generated by Django 4.2.7 on 2024-11-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0046_alter_permanentsubject_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanentsubject',
            name='branch_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
