# Generated by Django 4.2.7 on 2024-11-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0047_permanentsubject_branch_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permanentsubject',
            old_name='branch_code',
            new_name='degree',
        ),
    ]
