# Generated by Django 4.2.7 on 2024-11-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0048_rename_branch_code_permanentsubject_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permanentsubject',
            name='credit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
