# Generated by Django 4.2.7 on 2024-11-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0050_semester_subjects_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanentsubject',
            name='acedemic_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
