# Generated by Django 4.2.7 on 2024-11-09 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0051_permanentsubject_acedemic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementrySubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manage.semester')),
                ('subjects', models.ManyToManyField(to='Manage.subject')),
            ],
        ),
    ]
