# Generated by Django 4.2.7 on 2024-11-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0052_complementrysubjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='subjects_finalized',
        ),
    ]
