# Generated by Django 4.2.7 on 2024-11-11 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0017_remove_student_temp_pass_student_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Manage', '0053_remove_semester_subjects_finalized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='students',
        ),
        migrations.AddField(
            model_name='semester',
            name='students',
            field=models.ManyToManyField(blank=True, to='StakeHolders.student'),
        ),
        migrations.CreateModel(
            name='SubjectChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
