# Generated by Django 4.2.7 on 2024-11-11 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0054_remove_stream_students_semester_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectchoices',
            name='available_choices',
            field=models.ManyToManyField(related_name='available_subjects', to='Manage.subject'),
        ),
        migrations.AddField(
            model_name='subjectchoices',
            name='finalized_choices',
            field=models.ManyToManyField(related_name='finalized_subjects', to='Manage.subject'),
        ),
        migrations.AddField(
            model_name='subjectchoices',
            name='semester',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='Manage.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectchoices',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
