# Generated by Django 4.2.7 on 2024-11-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0055_subjectchoices_available_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectchoices',
            name='available_choices',
            field=models.ManyToManyField(blank=True, related_name='available_subjects', to='Manage.subject'),
        ),
        migrations.AlterField(
            model_name='subjectchoices',
            name='finalized_choices',
            field=models.ManyToManyField(blank=True, related_name='finalized_subjects', to='Manage.subject'),
        ),
    ]
