# Generated by Django 4.2.7 on 2024-11-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0056_alter_subjectchoices_available_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpscoordinates',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
