# Generated by Django 4.2.7 on 2024-11-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0057_gpscoordinates_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
    ]
