# Generated by Django 4.2.7 on 2024-11-11 12:13

from django.db import migrations, models
from django.utils import timezone
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0058_subject_is_elective'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectchoices',
            name='deadline_timestamp',
            field=models.DateTimeField(default=timezone.now() + timedelta(days=1)),
            preserve_default=False,
        ),
    ]
