# Generated by Django 4.2.7 on 2024-11-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0059_subjectchoices_deadline_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectchoices',
            name='choices_locked',
            field=models.BooleanField(default=False),
        ),
    ]
