# Generated by Django 4.2.7 on 2024-11-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0060_subjectchoices_choices_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectchoices',
            name='deadline_timestamp',
            field=models.DateField(),
        ),
    ]
