# Generated by Django 4.2.7 on 2024-11-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0061_alter_subjectchoices_deadline_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='complementrysubjects',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
