# Generated by Django 4.2.7 on 2024-11-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0062_complementrysubjects_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectchoices',
            name='finalized_choices',
        ),
        migrations.CreateModel(
            name='OrderedFinalizedSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.subject')),
                ('subject_choices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.subjectchoices')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
    ]
