# Generated by Django 4.2.7 on 2024-11-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0063_remove_subjectchoices_finalized_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectchoices',
            name='finalized_choices',
            field=models.ManyToManyField(blank=True, related_name='finalized_subjects', through='Manage.OrderedFinalizedSubject', to='Manage.subject'),
        ),
    ]
