# Generated by Django 4.2.7 on 2024-11-14 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0064_subjectchoices_finalized_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectchoices',
            name='deadline_timestamp',
        ),
        migrations.AddField(
            model_name='semester',
            name='subject_choice_deadline',
            field=models.DateField(default=datetime.date(2024, 11, 14)),
            preserve_default=False,
        ),
    ]
