# Generated by Django 4.2.7 on 2024-11-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0065_remove_subjectchoices_deadline_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='subject_choice_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
