# Generated by Django 4.2.7 on 2024-11-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0066_alter_semester_subject_choice_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='subjects_locked',
            field=models.BooleanField(default=False),
        ),
    ]
