# Generated by Django 4.2.7 on 2024-11-16 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0017_remove_student_temp_pass_student_is_active'),
        ('Manage', '0067_semester_subjects_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manage.semester')),
                ('students', models.ManyToManyField(blank=True, to='StakeHolders.student')),
                ('subjects', models.ManyToManyField(blank=True, to='Manage.subject')),
            ],
        ),
    ]
