# Generated by Django 4.2.7 on 2024-11-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0017_remove_student_temp_pass_student_is_active'),
        ('Manage', '0068_subjectgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='students',
            field=models.ManyToManyField(blank=True, to='StakeHolders.student'),
        ),
    ]
