# Generated by Django 4.2.7 on 2024-11-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0069_division_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='students',
        ),
        migrations.AddField(
            model_name='division',
            name='subject_groups',
            field=models.ManyToManyField(blank=True, to='Manage.subjectgroups'),
        ),
    ]
