# Generated by Django 4.2.7 on 2024-11-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0070_remove_division_students_division_subject_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='subject_groups',
        ),
    ]
