# Generated by Django 4.2.7 on 2024-11-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0071_remove_division_subject_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_technical',
            field=models.BooleanField(default=True),
        ),
    ]
