# Generated by Django 4.2.7 on 2024-11-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectchoicealerts',
            name='status',
            field=models.CharField(choices=[['unseen', 'Unseen'], ['seen', 'Seen']], default='unseen', max_length=20),
        ),
    ]
