# Generated by Django 4.2.7 on 2024-11-11 13:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Alerts', '0002_alter_subjectchoicealerts_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectChoiceAlerts',
            new_name='Alert',
        ),
    ]
