# Generated by Django 4.2.7 on 2024-11-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0003_rename_subjectchoicealerts_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('subject_choice_alert', 'Subject Choice Alert')], default='subject_choice_alert', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('unseen', 'Unseen'), ('seen', 'Seen')], default='unseen', max_length=20),
        ),
    ]
