# Generated by Django 4.2.7 on 2024-11-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0004_alert_type_alter_alert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('subject_choice_alert', 'Subject Choice Alert'), ('subject_deletion_alert', 'Subject Deletion Alert'), ('subject_choice_deadline_alert', 'Subject Choice Deadline Alert'), ('subject_choice_reset_alert', 'Subject Choice Reset Alert')], max_length=255),
        ),
    ]
