# Generated by Django 4.2.7 on 2023-11-24 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0001_initial'),
        ('TimeTable', '0008_alter_lecture_end_time_alter_lecture_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Session.session'),
        ),
    ]
