# Generated by Django 4.2.7 on 2023-11-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0003_alter_session_attendance'),
        ('TimeTable', '0009_alter_lecture_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Session.session'),
        ),
    ]
