# Generated by Django 4.2.7 on 2023-11-25 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0013_remove_student_signature_link'),
        ('TimeTable', '0010_alter_lecture_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='teacher_proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proxy', to='StakeHolders.teacher'),
        ),
    ]
