# Generated by Django 4.2.7 on 2024-01-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='signature_link',
        ),
        migrations.RemoveField(
            model_name='student',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='student',
            name='thank_you_response',
        ),
        migrations.AddField(
            model_name='student',
            name='device_id',
            field=models.CharField(default='1dsda112', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
