# Generated by Django 4.2.7 on 2024-01-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0004_remove_student_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='device_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
