# Generated by Django 4.2.7 on 2024-01-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0005_alter_student_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
