# Generated by Django 4.2.7 on 2024-10-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0012_rename_type_notificationsubscriptions_subscription_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsubscriptions',
            name='subscription_type',
        ),
        migrations.AddField(
            model_name='notificationsubscriptions',
            name='subscription_typ',
            field=models.CharField(blank=True, choices=[('lectures', 'Lectures'), ('alerts', 'Alerts')], max_length=10, null=True),
        ),
    ]
