# Generated by Django 4.2.7 on 2024-11-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0015_teacher_teacher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='temp_pass',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
