# Generated by Django 4.2.7 on 2024-11-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0016_student_temp_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='temp_pass',
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
